# Generated by Django 5.2.17 on 2026-09-08 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "source_document_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("EMAIL", "Email"),
                            ("NOTICE", "Notice"),
                            ("PHOTO", "Photo"),
                            ("PDF", "PDF"),
                            ("PURCHASE_CONFIRMATION", "Purchase confirmation"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=40,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("sender", models.CharField(blank=True, max_length=255)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("raw_text", models.TextField(blank=True)),
                ("content_hash", models.CharField(max_length=128)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSING", "Processing"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=30,
                    ),
                ),
                (
                    "uploaded_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="households.membership",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_documents",
                        to="households.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "subject"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedField",
            fields=[
                (
                    "extracted_field_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("field_path", models.CharField(max_length=150)),
                ("raw_value", models.TextField(blank=True)),
                ("extracted_value", models.TextField(blank=True)),
                ("confirmed_value", models.TextField(blank=True)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SUGGESTED", "Suggested"),
                            ("CONFIRMED", "Confirmed"),
                            ("CORRECTED", "Corrected"),
                            ("REJECTED", "Rejected"),
                            ("UNRESOLVED", "Unresolved"),
                        ],
                        default="SUGGESTED",
                        max_length=30,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_extracted_fields",
                        to="households.membership",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_fields",
                        to="intake.sourcedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["source_document", "field_path"],
            },
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("workspace", "content_hash"),
                name="unique_document_hash_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractedfield",
            constraint=models.UniqueConstraint(
                fields=("source_document", "field_path"),
                name="unique_field_path_per_document",
            ),
        ),
    ]
