# Generated by Django 5.2.17 on 2026-09-08 01:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        ("intake", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("CHORE", "Chore"),
                            ("APPOINTMENT", "Appointment"),
                            ("DEADLINE", "Deadline"),
                            ("ERRAND", "Errand"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SHOPPING", "Shopping"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=40,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("recurrence_rule", models.CharField(blank=True, max_length=255)),
                ("default_location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to="households.membership",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_tasks",
                        to="inventory.product",
                    ),
                ),
                (
                    "related_shopping_list_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_tasks",
                        to="inventory.shoppinglistentry",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_tasks",
                        to="intake.sourcedocument",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="households.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="TaskOccurrence",
            fields=[
                (
                    "task_occurrence_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("OFFER_PENDING", "Offer pending"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In progress"),
                            ("REPORTED_COMPLETE", "Reported complete"),
                            ("SKIPPED", "Skipped"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="workflows.task",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "task__title"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("offered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("response_cutoff_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OFFERED", "Offered"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("UNANSWERED", "Unanswered"),
                            ("REASSIGNED", "Reassigned"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="OFFERED",
                        max_length=30,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offered_to_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_assignments",
                        to="households.membership",
                    ),
                ),
                (
                    "proposed_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_assignments",
                        to="households.membership",
                    ),
                ),
                (
                    "task_occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="workflows.taskoccurrence",
                    ),
                ),
            ],
            options={
                "ordering": ["-offered_at", "task_occurrence"],
            },
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("workspace", "title"), name="unique_task_title_per_workspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskoccurrence",
            constraint=models.UniqueConstraint(
                fields=("task", "sequence"), name="unique_sequence_per_task"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("task_occurrence", "attempt_number"),
                name="unique_assignment_attempt_per_occurrence",
            ),
        ),
    ]
