# Generated by Django 5.2.17 on 2026-09-08 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("canonical_name", models.CharField(max_length=150)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("default_unit", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="households.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace__name", "category", "canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListEntry",
            fields=[
                (
                    "shopping_list_entry_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("item_name", models.CharField(max_length=150)),
                (
                    "suggested_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SUGGESTED", "Suggested"),
                            ("ACCEPTED", "Accepted"),
                            ("DISMISSED", "Dismissed"),
                            ("PURCHASED", "Purchased"),
                            ("REMOVED", "Removed"),
                        ],
                        default="SUGGESTED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shopping_list_entries",
                        to="households.membership",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_list_entries",
                        to="inventory.product",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_list_entries",
                        to="households.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="SupplyItem",
            fields=[
                ("supply_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_tracked", models.BooleanField(default=True)),
                (
                    "target_level",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("quantity_unit", models.CharField(max_length=30)),
                ("last_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_updated_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_supply_items",
                        to="households.membership",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_items",
                        to="households.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace__name", "product__canonical_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("workspace", "canonical_name"),
                name="unique_product_name_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplyitem",
            constraint=models.UniqueConstraint(
                fields=("workspace", "product"),
                name="unique_tracked_product_per_workspace",
            ),
        ),
    ]
