# Generated by Django 5.2.17 on 2026-09-08 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("membership_id", models.AutoField(primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADULT", "Adult"),
                            ("CHILD", "Child"),
                            ("CAREGIVER", "Caregiver"),
                            ("LIMITED", "Limited"),
                            ("OTHER", "Other"),
                        ],
                        default="ADULT",
                        max_length=30,
                    ),
                ),
                ("can_manage_sources", models.BooleanField(default=False)),
                ("can_assign_tasks", models.BooleanField(default=False)),
                ("can_receive_assignments", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hestia_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["workspace__name", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("workspace_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "workspace_type",
                    models.CharField(
                        choices=[("HOUSEHOLD", "Household"), ("TEAM", "Team")],
                        default="HOUSEHOLD",
                        max_length=30,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Chicago", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="hestia_workspaces",
                        through="households.Membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="households.workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user"),
                name="unique_user_membership_per_workspace",
            ),
        ),
    ]
